### ISSUE TITLE
Should 'context' be '@context'?

### ISSUE THREAD

**Issue by hacdias** [go-ap/activitypub#11]
I was considering using this library to encode some ActivityPub data I have on my website. However, I noticed that the `Context` field gets serialised to `context` and not `@context`. Is that on purpose? If so, why? And how could I output it as `@context`?

**Comment by ghost** [comment]
I remember running into this issue while working on Gitea federation a few months ago. My solution was to use `jsonld.WithContext` as you can see [here](https://gitea.com/xy/gitea/src/commit/439f6754acd1045ed4387e19f240f213b5221fdb/routers/api/v1/activitypub/response.go#L21).

**Comment by hacdias** [comment]
Thanks @Ta180m!

**Comment by hacdias** [comment]
It would be great to get some feedback from the author though, cc @mariusor. I would like to understand if this is a bug, or on purpose.

**Comment by ghost** [comment]
Maybe ask about this on the [mailing list](https://lists.sr.ht/~mariusor/activitypub-go)?

**Comment by mariusor** [comment]
Hey @hacdias, apologies for the late reply.

So, @ta180m is right on all accounts:

I prefer the mailing list for questions because on github usually nothing happens, and it's more convenient for me to talk over email.

To use the JSON-LD @context, you need to use the mechanism suggested:

```go
body, err := jsonld.WithContext(
    jsonld.IRI(vocab.ActivityBaseURI),
    jsonld.IRI(vocab.SecurityContextURI),
).Marshal(a)
```

The `Context` property that you mentioned on the go-ap objects stems from the [ActivityStreams vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-context) specification, and has nothing to do with the JSON-LD context, though I can understand the confusion. It should be commented in the source code with the details from the spec itself, which I was hoping that it gives an indication about its purpose.

**Comment by hacdias** [comment]
@mariusor thanks for the context - no pun intended. I will then close this issue as it is not a bug!
